<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2019-11-07T16:19:25+03:00" hostname="https://cats-inna-dev-ed.my.salesforce.com" tests="1" failures="1"  errors="0"  time="0.37">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Nov 7, 2019 4:19 PM"/>
            <property name="testExecutionTime" value="0.37 s"/>
            <property name="testTotalTime" value="0.37 s"/>
            <property name="commandTime" value="3.22 s"/>
            <property name="hostname" value="https://cats-inna-dev-ed.my.salesforce.com"/>
            <property name="orgId" value="00D2p0000013mwyEAA"/>
            <property name="username" value="inna.stolyarova@vrp.dev.comnsulting.com"/>
            <property name="testRunId" value="7072p00007Ja8Oe"/>
            <property name="userId" value="0052p000009LlzYAAS"/>
            <property name="testRunCoverage" value="76%"/>
            <property name="orgWideCoverage" value="31%"/>
        </properties>
        <testcase name="updateOpportunityTest" classname="TestCopyOrders" time="0.37">
            <failure message="System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, OpportunityCopyTrigger: execution of AfterInsert

caused by: System.FinalException: Record is read-only

Class.HandlerOpportunityWebOrder.addWebOrderFromOpporunity: line 54, column 1
Trigger.OpportunityCopyTrigger: line 3, column 1: []"><![CDATA[Class.TestOpportunityFactory.addOpportunity: line 23, column 1
Class.TestCopyOrders.updateOpportunityTest: line 24, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
