<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2019-08-29T14:08:02+03:00" hostname="https://efficiency-inspiration-8299-dev-ed.cs102.my.salesforce.com/" tests="1" failures="1"  errors="0"  time="0.88">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Aug 29, 2019 2:08 PM"/>
            <property name="testExecutionTime" value="0.88 s"/>
            <property name="testTotalTime" value="0.88 s"/>
            <property name="commandTime" value="4.82 s"/>
            <property name="hostname" value="https://efficiency-inspiration-8299-dev-ed.cs102.my.salesforce.com/"/>
            <property name="orgId" value="00D1j0000000TebEAE"/>
            <property name="username" value="test-o2pamexq65qp@example.com"/>
            <property name="testRunId" value="7071j00000TbHA9"/>
            <property name="userId" value="0051j000001zCRHAA2"/>
            <property name="testRunCoverage" value="68%"/>
            <property name="orgWideCoverage" value="68%"/>
        </properties>
        <testcase name="TestAddOpportunity" classname="TestCopyOrders" time="0.88">
            <failure message="System.AssertException: Assertion Failed: Expected: 0011j00000K6r7AAAR, Actual: null"><![CDATA[Class.TestCopyOrders.TestAddOpportunity: line 27, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
